### ISSUE TITLE
对于源码想请教一下

### ISSUE THREAD

**Issue by MaskWu** [beilunyang/cnodejs-vue#1]
在看cnodejs-vue中 看到了这种写法
`export const getLoginUser = (state) => state.loginUser;`
`export const changeUser = ({ dispatch }, info) => dispatch('CHANGE_USER', info);`
其中在export时 为什么先等于一个括号包含的值之后再指向export的方法，
刚接触es6，一直没有查到相关的知识，博主有相关的文档给我参考一下吗

**Comment by beilunyang** [comment]
const changeUser = function({ dispatch }, info) {
    dispatch('CHANGE_USER', info);
}
就只是函数表达式的箭头函数写法而已！es6可以看看阮一峰老师的开源书

**Comment by MaskWu** [comment]
ok 好的 非常感谢
